# Generated by Django 5.2.4 on 2025-07-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_users',
        ),
    ]
