# Generated by Django 5.2.4 on 2025-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
