# Generated by Django 5.2.4 on 2025-07-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tbl_employment_type',
            },
        ),
        migrations.CreateModel(
            name='JobApplicationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tbl_job_application_status',
            },
        ),
        migrations.CreateModel(
            name='WorkArrangement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tbl_work_arrangement',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_title', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('job_posting_link', models.CharField(max_length=255)),
                ('date_applied', models.DateField()),
                ('company_logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('job_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_type', to='job_applications.employmenttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to=settings.AUTH_USER_MODEL)),
                ('job_application_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_status', to='job_applications.jobapplicationstatus')),
                ('work_arrangement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_arrangement', to='job_applications.workarrangement')),
            ],
            options={
                'db_table': 'tbl_job_application',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isReminderUsed', models.BooleanField(default=False)),
                ('time_set', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('job_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='job_applications.jobapplication')),
            ],
            options={
                'db_table': 'tbl_reminders',
            },
        ),
    ]
