# Generated by Django 5.2.4 on 2025-07-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reminder',
            table='tbl_reminder',
        ),
    ]
