# Generated by Django 5.2.4 on 2025-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_alter_reminder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
