# Generated by Django 5.2.4 on 2025-07-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0003_jobapplication_job_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='user_id',
            new_name='user',
        ),
    ]
