# Generated by Django 5.2.4 on 2025-07-31 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0004_rename_user_id_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='isReminderUsed',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='time_set',
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
