# Generated by Django 5.2.4 on 2025-07-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0005_remove_reminder_isreminderused_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='job_application_id',
            new_name='job_application',
        ),
    ]
