# Generated by Django 5.2.4 on 2025-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0006_rename_job_application_id_reminder_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company_logo_url',
        ),
    ]
