# Generated by Django 5.2.4 on 2025-08-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0007_remove_jobapplication_company_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
