# Generated by Django 5.2.4 on 2025-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0008_alter_jobapplication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
